"""
Process HD ability icons into pixel-perfect 24x24 sprites
and fire_spear projectile into 16x16.
Uses nearest-neighbor resampling (NEAREST) for hard pixel edges.
Enforces Círculo VII color palette.
"""

from PIL import Image
import os
import sys

# Source images (generated by Antigravity)
BRAIN_DIR = os.path.expanduser(
    r"~\.gemini\antigravity\brain\8854404f-bd45-4f40-8c35-b89b02be672f"
)

# Find the actual files (they have timestamp suffixes)
def find_image(prefix):
    """Find the most recent image matching a prefix in the brain dir."""
    candidates = [f for f in os.listdir(BRAIN_DIR) if f.startswith(prefix) and f.endswith('.png')]
    if not candidates:
        print(f"  WARNING: No image found for prefix '{prefix}'")
        return None
    # Sort by name (timestamp suffix) and pick latest
    candidates.sort()
    return os.path.join(BRAIN_DIR, candidates[-1])


# Círculo VII palette - dark infernal colors
CIRCULO_VII_PALETTE = [
    # Blacks/Darks
    (0, 0, 0),        # Pure black
    (20, 12, 12),     # Near black warm
    (35, 20, 15),     # Dark brown
    (45, 25, 20),     # Darker brown
    # Reds
    (80, 20, 15),     # Dark red
    (120, 30, 20),    # Blood red
    (160, 40, 25),    # Crimson
    (180, 50, 30),    # Bright red
    (200, 60, 35),    # Fire red
    # Oranges
    (180, 80, 30),    # Dark orange
    (200, 100, 40),   # Orange
    (220, 140, 50),   # Bright orange
    (240, 170, 60),   # Gold-orange
    # Yellows/Golds
    (200, 160, 60),   # Muted gold
    (220, 190, 80),   # Gold
    (240, 210, 100),  # Bright gold
    (255, 230, 130),  # Light gold
    # Blues (dark, for ice)
    (20, 25, 50),     # Very dark blue
    (30, 40, 80),     # Dark blue
    (50, 60, 110),    # Medium dark blue
    (70, 90, 140),    # Blue
    (100, 130, 170),  # Light blue
    # Purples (for shadow)
    (30, 15, 40),     # Very dark purple
    (50, 25, 60),     # Dark purple
    (70, 35, 90),     # Purple
    (100, 50, 120),   # Bright purple
    # Whites/Grays
    (60, 55, 50),     # Dark gray warm
    (90, 85, 80),     # Gray
    (120, 115, 110),  # Light gray
    (160, 155, 150),  # Lighter gray
    (200, 195, 190),  # Near white
    (230, 225, 220),  # Off white
    (255, 255, 255),  # White
    # Greens (for toxic, muted)
    (30, 50, 20),     # Dark green
    (50, 80, 30),     # Green
    # Metallic
    (100, 100, 110),  # Steel gray
    (140, 140, 150),  # Light steel
]

def closest_palette_color(r, g, b):
    """Find the closest palette color using euclidean distance."""
    min_dist = float('inf')
    best = (0, 0, 0)
    for pr, pg, pb in CIRCULO_VII_PALETTE:
        dist = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if dist < min_dist:
            min_dist = dist
            best = (pr, pg, pb)
    return best


def process_icon(src_path, dst_path, target_size, apply_palette=True):
    """Downscale image to target_size with nearest-neighbor and optional palette."""
    if src_path is None:
        return False
    
    img = Image.open(src_path).convert("RGBA")
    
    # Resize with nearest neighbor
    img = img.resize(target_size, Image.NEAREST)
    
    if apply_palette:
        # Apply palette to non-transparent pixels
        pixels = img.load()
        w, h = img.size
        for y in range(h):
            for x in range(w):
                r, g, b, a = pixels[x, y]
                if a > 20:  # Not transparent
                    nr, ng, nb = closest_palette_color(r, g, b)
                    pixels[x, y] = (nr, ng, nb, a)
    
    img.save(dst_path)
    file_size = os.path.getsize(dst_path)
    print(f"  OK: {dst_path} ({target_size[0]}x{target_size[1]}, {file_size} bytes)")
    return True


def main():
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    abilities_dir = os.path.join(project_root, "assets", "sprites", "abilities")
    fx_dir = os.path.join(project_root, "assets", "sprites", "fx")
    
    os.makedirs(abilities_dir, exist_ok=True)
    os.makedirs(fx_dir, exist_ok=True)
    
    print("=== Processing Ability Icons (24x24) ===\n")
    
    icons = [
        ("icon_lanza_flegetonte", "lanza_flegetonte.png"),
        ("icon_escudo_hielo", "escudo_hielo.png"),
        ("icon_paso_sombrio", "paso_sombrio.png"),
        ("icon_grito_guerra", "grito_guerra.png"),
        ("icon_drenar_alma", "drenar_alma.png"),
    ]
    
    success_count = 0
    for prefix, filename in icons:
        src = find_image(prefix)
        dst = os.path.join(abilities_dir, filename)
        if process_icon(src, dst, (24, 24)):
            success_count += 1
    
    print(f"\n  {success_count}/5 icons processed\n")
    
    print("=== Processing Fire Spear Projectile (16x16) ===\n")
    
    src = find_image("sprite_fire_spear")
    dst = os.path.join(fx_dir, "fire_spear.png")
    if process_icon(src, dst, (16, 16)):
        print("\n  Projectile processed successfully\n")
    else:
        print("\n  FAILED: fire_spear not found\n")
    
    print("=== DONE ===")


if __name__ == "__main__":
    main()
